name: PR Build Deploy

on:
  pull_request_target:
    types: [labeled]

env:
  PORT: ${{secrets.PR_PORT}}
  MONGO_APP_URL: ${{secrets.MONGO_APP_URL}}
  SESSION_SECRET: ${{secrets.SESSION_SECRET}}
  DEV_KEY: ${{secrets.DEV_KEY}}
  DEV_KEY_EXP: ${{secrets.DEV_KEY_EXP}}
  TYPE: ${{secrets.TYPE}}
  PROJECT_ID: ${{secrets.PROJECT_ID}}
  PRIVATE_KEY_ID: ${{secrets.PRIVATE_KEY_ID}}
  PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
  CLIENT_EMAIL: ${{secrets.CLIENT_EMAIL}}
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  AUTH_URI: ${{secrets.AUTH_URI}}
  TOKEN_URI: ${{secrets.TOKEN_URI}}
  AUTH_PROVIDER_X509_CERT_URL: ${{secrets.AUTH_PROVIDER_X509_CERT_URL}}
  CLIENT_X509_CERT_URL: ${{secrets.CLIENT_X509_CERT_URL}}

jobs:
  pr-build-deploy:
    runs-on: [self-hosted, aptiche-pr]
    if: contains(github.event.pull_request.labels.*.name, 'safe-for-build')
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Deploy Staging Server
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create .env File
        run: |
          touch .env
          echo PORT=$PORT >> .env
          echo MONGO_APP_URL=$MONGO_APP_URL >> .env
          echo SESSION_SECRET=$SESSION_SECRET >> .env
          echo DEV_KEY=$DEV_KEY >> .env
          echo DEV_KEY_EXP=$DEV_KEY_EXP >> .env
          echo TYPE=$TYPE >> .env
          echo PROJECT_ID=$PROJECT_ID >> .env
          echo PRIVATE_KEY_ID=$PRIVATE_KEY_ID >> .env
          echo PRIVATE_KEY=\"$PRIVATE_KEY\" >> .env
          echo CLIENT_EMAIL=$CLIENT_EMAIL >> .env
          echo CLIENT_ID=$CLIENT_ID >> .env
          echo AUTH_URI=$AUTH_URI >> .env
          echo TOKEN_URI=$TOKEN_URI >> .env
          echo AUTH_PROVIDER_X509_CERT_URL=$AUTH_PROVIDER_X509_CERT_URL >> .env
          echo CLIENT_X509_CERT_URL=$CLIENT_X509_CERT_URL >> .env
          cat .env
      - run: yarn
      - run: tsc
      - run: pm2 restart nutella-pr
